const {ERROR, OFF} = require('../shared');

module.exports = {
  rules: {
    'comma-dangle': [ERROR, 'always-multiline'],
    'for-direction': ERROR,
    'getter-return': [ERROR, {allowImplicit: true}],
    'no-await-in-loop': ERROR,
    'no-compare-neg-zero': ERROR,
    'no-cond-assign': ERROR,
    'no-console': ERROR,
    'no-constant-condition': ERROR,
    'no-control-regex': ERROR,
    'no-debugger': ERROR,
    'no-dupe-args': ERROR,
    'no-dupe-keys': ERROR,
    'no-duplicate-case': ERROR,
    'no-empty': ERROR,
    'no-empty-character-class': ERROR,
    'no-ex-assign': ERROR,
    'no-extra-boolean-cast': ERROR,
    'no-extra-parens': OFF,
    'no-extra-semi': ERROR,
    'no-func-assign': ERROR,
    'no-inner-declarations': [ERROR, 'functions'],
    'no-invalid-regexp': ERROR,
    'no-irregular-whitespace': ERROR,
    'no-multi-assign': ERROR,
    'no-obj-calls': ERROR,
    'no-prototype-builtins': ERROR,
    'no-regex-spaces': ERROR,
    'no-sparse-arrays': ERROR,
    'no-unexpected-multiline': ERROR,
    'no-unreachable': ERROR,
    'no-unsafe-finally': ERROR,
    'no-unsafe-negation': ERROR,
    'no-template-curly-in-string': ERROR,
    'use-isnan': ERROR,
    'valid-jsdoc': [
      2,
      {
        prefer: {
          return: 'returns',
        },
      },
    ],
    'valid-typeof': ERROR,
  },
};
