const {ERROR, OFF} = require('../shared');

module.exports = {
  rules: {
    'array-bracket-newline': [ERROR, 'consistent'],
    'array-bracket-spacing': [ERROR, 'never'],
    'array-element-newline': [ERROR, {multiline: true, minItems: 3}],
    'block-spacing': ERROR,
    'brace-style': [ERROR, '1tbs', {allowSingleLine: true}],
    camelcase: ERROR,
    'capitalized-comments': [
      OFF,
      'never',
      {
        line: {
          ignorePattern: '.*',
          ignoreInlineComments: true,
          ignoreConsecutiveComments: true,
        },
        block: {
          ignorePattern: '.*',
          ignoreInlineComments: true,
          ignoreConsecutiveComments: true,
        },
      },
    ],
    'comma-spacing': ERROR,
    'comma-style': [ERROR, 'last'],
    'computed-property-spacing': OFF,
    'consistent-this': [ERROR, 'self'],
    'eol-last': ERROR,
    'func-call-spacing': [ERROR, 'never'],
    'func-name-matching': [
      OFF,
      'always',
      {
        includeCommonJSModuleExports: false,
      },
    ],
    'func-names': OFF,
    'func-style': [OFF, 'declaration'],
    'function-paren-newline': [ERROR, 'multiline'],
    'id-blacklist': [OFF, 'data', 'err', 'e', 'cb', 'callback'],
    'id-length': OFF,
    'id-match': OFF,
    'implicit-arrow-linebreak': [ERROR, 'beside'],
    indent: [ERROR, 2, {SwitchCase: 1}],
    'jsx-quotes': [ERROR, 'prefer-double'],
    'key-spacing': [ERROR, {beforeColon: false, afterColon: true}],
    'keyword-spacing': ERROR,
    'lines-around-comment': OFF,
    'lines-between-class-members': [
      ERROR,
      'always',
      {exceptAfterSingleLine: false},
    ],
    'line-comment-position': [
      OFF,
      {
        position: 'above',
        ignorePattern: '',
        applyDefaultPatterns: true,
      },
    ],
    'linebreak-style': [OFF, 'unix'],
    'max-nested-callbacks': [OFF, 2],
    'multiline-comment-style': [OFF, 'starred-block'],
    'multiline-ternary': OFF,
    'new-cap': [ERROR, {newIsCap: true, capIsNew: false}],
    'new-parens': ERROR,
    'newline-per-chained-call': OFF,
    'no-array-constructor': ERROR,
    'no-continue': OFF,
    'no-inline-comments': OFF,
    'no-lonely-if': OFF,
    'no-mixed-operators': ERROR,
    'no-mixed-spaces-and-tabs': [ERROR, false],
    'no-multiple-empty-lines': [OFF, {max: 2}],
    'no-nested-ternary': OFF,
    'no-negated-condition': ERROR,
    'no-new-object': ERROR,
    'no-restricted-syntax': OFF,
    'no-tabs': ERROR,
    'no-ternary': OFF,
    'no-trailing-spaces': ERROR,
    'no-underscore-dangle': ERROR,
    'no-unneeded-ternary': OFF,
    'no-whitespace-before-property': ERROR,
    'object-curly-newline': OFF,
    'object-curly-spacing': OFF,
    'one-var': OFF,
    'one-var-declaration-per-line': [OFF, 'always'],
    'operator-assignment': [OFF, 'always'],
    'operator-linebreak': OFF,
    'padded-blocks': OFF,
    'quote-props': [ERROR, 'as-needed'],
    quotes: [ERROR, 'single', 'avoid-escape'],
    'require-jsdoc': OFF,
    semi: ERROR,
    'semi-spacing': [ERROR, {before: false, after: true}],
    'semi-style': [ERROR, 'last'],
    'sort-keys': [OFF, 'asc', {caseSensitive: false, natural: true}],
    'sort-vars': OFF,
    'sort-imports': OFF,
    'space-before-blocks': [ERROR, 'always'],
    'space-before-function-paren': [ERROR, 'never'],
    'space-in-parens': [ERROR, 'never'],
    'space-infix-ops': ERROR,
    'space-unary-ops': [ERROR, {words: true, nonwords: false}],
    'spaced-comment': [ERROR, 'always'],
    'switch-colon-spacing': [ERROR, {after: true, before: false}],
    'template-tag-spacing': [ERROR, 'never'],
    'unicode-bom': [OFF, 'never'],
    'wrap-regex': OFF,
  },
};
